### ISSUE TITLE
istio auto sidecar injection doesn't work with flannel as CNI(Container Network Interface) tool

### ISSUE THREAD

**Issue by hiondal** [flannel-io/flannel#1259]
istio auto sidecar injection doesn't work with flannel as CNI(Container Network Interface) tool.   

## Expected Behavior

I expect istio auto sidecar injection works as followed.   
https://istio.io/docs/setup/additional-setup/sidecar-injection/#automatic-sidecar-injection

## Current Behavior

when I apply auto sidecar injection, a Pod never is created.    
Refer below issue ticket on istio github.   
https://github.com/istio/istio/issues/21058   

## Possible Solution

No way without changing CNI from flannel to calico.   

## Steps to Reproduce (for bugs)

1. install kubernetes cluster with kubeadm.   during setup, install flannel as CNI.
2. install istio. 
3.apply audo sidecar injection to default OR you created namespace.
4.Test it.    
refer below link..   
https://istio.io/docs/setup/additional-setup/sidecar-injection/#disabling-or-updating-the-webhook

## Your Environment

* Flannel version:I'm not sure. I install latest version at March 2020.
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used): 1.7X
* Operating System and version: centos7
* Link to your project (optional):

**Comment by DesistDaydream** [comment]
If you change the working mode of flannel to 'host-gw', this problem should be solved.
If not, you can install 'kube-state-metrics' and try.

**Comment by davesargrad** [comment]
I have host-gw set, and this still does not work for me. i also see a failure to inject the sidecar using the bookinfo sample app. 

![image](https://user-images.githubusercontent.com/48793689/79990011-86c49f80-847e-11ea-82e4-02e38aa19ef8.png)

**Comment by DesistDaydream** [comment]
@davesargrad you can install 'kube-state-metrics' and try.

**Comment by jnicholls** [comment]
I am also running into this problem with Istio 1.6.2. This was not a problem with Istio 1.4.x.

Can someone explain why `kube-state-metrics` would have any sort of effect on the api-server's ability to speak to an in-cluster service?

**Comment by ragunathan23** [comment]
I m facing the same issue with istio 1.5.2. Any help here?

**Comment by ragunathan23** [comment]
It's a flannel issue. For now able to fix the issue by changing the flannel backend to host-gw from vxlan. Not sure why it didn't work with vxlan. Thanks for @nustiueudinastea (Alex) for debugging the issue.

**Comment by northonheld** [comment]
@ragunathan23 thanks for reporting the flannel problem here. I solved my problem by switching to host-gw. Thank you very much.
